export const login = () => {
  const loginDiv = document.createElement('div');
  loginDiv.setAttribute('class', 'loginView');
  const titleLogin = document.createElement('h1');
  const emailInput = document.createElement('input');
  const passwordInput = document.createElement('input');
  const passwordForget = document.createElement('a');
  const intoButton = document.createElement('button');
  const intoParagraph = document.createElement('p');
  const divIcons = document.createElement('div');
  divIcons.setAttribute('class', 'iconDivLogin');
  const imgIconFacebook = document.createElement('img');
  const imgIconGmail = document.createElement('img');
  const newParagraph = document.createElement('p');
  const createAccount = document.createElement('button');
  titleLogin.textContent = 'INICIAR SESIÓN';
  titleLogin.setAttribute('id', 'titleLogin');
  emailInput.setAttribute('id', 'emailInto');
  emailInput.textContent = 'Correo';
  emailInput.setAttribute('type', 'email');
  emailInput.setAttribute('placeholder', 'Correo');
  emailInput.setAttribute('placeholder', 'Correo');
  emailInput.setAttribute('required', '');
  passwordInput.setAttribute('id', 'passwordInto');
  passwordInput.textContent = 'Contraseña';
  passwordInput.setAttribute('type', 'password');
  passwordInput.setAttribute('placeholder', 'Contraseña');
  passwordInput.setAttribute('required', '');
  passwordForget.textContent = '¿Olvidaste tu contraseña?';
  passwordForget.setAttribute('id', 'textPasswordForget');
  intoButton.textContent = 'INGRESAR';
  intoButton.setAttribute('id', 'btnLogin');
  intoButton.setAttribute('class', 'btnLogin');
  intoParagraph.textContent = 'O ingresa con';
  intoParagraph.setAttribute('id', 'textIntoParagraph');
  divIcons.appendChild(imgIconFacebook);
  divIcons.appendChild(imgIconGmail);
  imgIconFacebook.setAttribute('src', 'img/facebook (2).png');
  imgIconFacebook.setAttribute('class', 'iconInto');
  imgIconGmail.setAttribute('src', 'img/google.png');
  imgIconGmail.setAttribute('class', 'iconInto');
  newParagraph.textContent = '¿Eres nuevo en PetWorld?';
  newParagraph.setAttribute('id', 'textNewParagraph');
  createAccount.textContent = 'Crea tu cuenta';
  createAccount.setAttribute('class', 'textCreateAccount');
  loginDiv.appendChild(titleLogin);
  loginDiv.appendChild(emailInput);
  loginDiv.appendChild(titleLogin);
  loginDiv.appendChild(emailInput);
  loginDiv.appendChild(passwordInput);
  loginDiv.appendChild(passwordForget);
  loginDiv.appendChild(intoButton);
  loginDiv.appendChild(intoParagraph);
  loginDiv.appendChild(divIcons);
  loginDiv.appendChild(newParagraph);
  loginDiv.appendChild(createAccount);

  return loginDiv;
};

